In [4]:
import pandas as pd
df=pd.read_csv('/content/customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

Step 1: Import libraries and load CSV

The dataset needs to be loaded for analysis. Using pandas, we read the CSV into a DataFrame and preview it to understand its structure.

In [ ]:
print("missing values per column:\n")
df.isnull().sum()

missing values per column:

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

Step 2: Check for missing values

Missing data can affect analysis and results. df.isnull().sum() identifies which columns have gaps so we can handle them appropriately.

In [ ]:
df['Review Rating']=df['Subscription Status'].fillna(df['Review Rating'].median)
print("missing values after cleaning:\n")
df.isnull().sum()

missing values after cleaning:

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

Step 3: Fill missing “Review Rating”

Missing review ratings can skew insights. We fill them with the median, which reduces the impact of outliers and preserves the overall data distribution

In [ ]:
print(f"duplicate values or row")
df.duplicated().sum()
df=df.drop_duplicates()
print("duplicate values removed")

duplicate values or row
duplicate values removed

Step 4: Remove duplicates

Duplicate rows can distort results. df.drop_duplicates() removes repeated entries to ensure each record is unique.

In [ ]:
categorical_cols=['Gender','Category','Location','Season']
for col in categorical_cols:
  df[col]=df[col].astype(str).str.strip().str.title()
print("\n Standard categorical columns:")
print(df[categorical_cols].head())

 Standard categorical columns:
  Gender  Category       Location  Season
0   Male  Clothing       Kentucky  Winter
1   Male  Clothing          Maine  Winter
2   Male  Clothing  Massachusetts  Spring
3   Male  Footwear   Rhode Island  Spring
4   Male  Clothing         Oregon  Spring

Step 5: Standardize categorical columns

Inconsistent text formatting can cause errors in analysis. We strip spaces and capitalize values to standardize columns like Gender, Category, Location, and Season.

In [ ]:

df['Age Group'] =pd.cut(df['Age'],bins=[0,30,50,100] , labels =['Young','Adult','Senior'])
print("\nage group distribution:")
print(df['Age Group'].value_counts())

age group distribution:
Age Group
Senior    1476
Adult     1475
Young      949
Name: count, dtype: int64

Step 6: Create age groups

Continuous age values are hard to analyze in segments. Using pd.cut(), we group ages into Young, Adult, and Senior categories for easier analysis.

In [ ]:

df.to_csv('cleaned_data_csv',index=False)
print("\nProcess complete, File saved as 'cleaned_data_csv'.")
df.head()

Process complete, File saved as 'cleaned_data_csv'.

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Age Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,Yes,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Senior
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,Yes,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,Yes,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Adult
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,Yes,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,Yes,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Adult

Step 7: Save the cleaned data

After cleaning, saving the dataset prevents repeating the process. df.to_csv() exports the cleaned, standardized data for future use.